### ISSUE TITLE
Didn't claim for some reason

### ISSUE THREAD

**Issue by gurendikun** [Insisted/NH_Income_Automation#1]
happened after new year, it was claiming like normal till 31 Dec but after new year it's not claiming anymore

**Comment by Insisted** [comment]
Thank you for opening a ticket,
I just tried running the script and it's definitely not working as intended.

I'm going to try and find the root cause of this issue.

Cheers!

**Comment by Insisted** [comment]
Dove down the issue,
and iturns out the [kageherostudio's reward claiming page](https://kageherostudio.com/event/?event=daily) did not use the proper `data-period` attribute, as it exceeded the 12 months count in a year (it's Januari, yet it uses the value 13).

For the colution, the script will not use the current month automatically, but will use the `data-period` attribute from within the page itself.

Going to push a fix ASAP.

**Comment by gurendikun** [comment]
can you look at my repo and tell me where i can fix this? https://github.com/dot-1x/nh_income

**Comment by gurendikun** [comment]
i've tried changing it multiple times in a clone one but didn't really work .-.
